services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - server:latest
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "5000:8080"  # Internal port only, not exposed directly
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./Server/Data:/app/Data
    restart: unless-stopped
    networks:
      - app-network

  caddy:
    image: caddy:2-alpine
    container_name: caddy-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - server

volumes:
  caddy-data:
  caddy-config:

networks:
  app-network:
    driver: bridge
