services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    volumes:
      - ./Server/Data:/app/Data  # Mount local data directory to container
    restart: unless-stopped
